training:
  model_name: 'textcnn'
  learning_rate: 0.8
  embedding_dim: 100
  maxlen: 128
  batch_size: 32
  epochs : 1
preprocessing:
  input_convertor: 'nn_vectorization'
  embedding_dim: 100
  maxlen: 128